const PROPERTIES = {
    BASEURL: 'https://api.themoviedb.org/3',
    TIMEOUT: 1000,
    HEADER: 'eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJmMzU3Yzk2ZGQ4MGE0ZGViMjRhYTY4YjU3NjNlM2Q5MyIsInN1YiI6IjYzMzVhZWQ4ZWRlYjQzMDA3YTFlZjg4OCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.71J7pHZkIwjYHV50KwpoLBlgEGkvSEKBw7vCCB2sRgA'
}

export default PROPERTIES